# Site settings
title: 菇星独行
SEOTitle: 菇歌 | Guogle
email: mgsweet@126.com
header-img: img/home-bg.jpg
description: "Mr.GU's Imagination"
keyword: ""
url: "http://mgsweet.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'
manger: Mr.GU

#authors' infomation
#use site.authors[page.author].name to access the author's name
authors:
  Mr.GU:
    name: Mr.GU
    email: mgsweet@126.com
    website: http://mgsweet.github.io
    github: mgsweet
    weibo: mgsweet
    QQ: 610879915



# SNS settings
RSS: false
weibo_username:     mgsweet
github_username:    mgsweet
facebook_username:  gulessness
zhihu_username:     mgsweet

#twitter_username:  mgsweet



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: "ruby"
    



# Disqus settings
disqus_username: mgsweet
# Duoshuo settings
#duoshuo_username: mgsweet
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "爱旅行，爱运动，更爱打码，做我所畅想，活我所喜爱"
sidebar-avatar: /img/self_image.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "join me",
        href: "#"
    }
]
